//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.13 at 06:08:56 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ebay.in/sales/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in.ebay.sales.products;
